version: 2
jobs:
build:
working_directory: ~/TestNewMaven
docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
- restore_cache:
key: TestNewMaven-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
- save_cache:
paths:
            - ~/.m2
          key: TestNewMaven-{{ checksum "pom.xml" }}
      
      - run: mvn package
- store_test_results:
- store_artifacts:
